/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhyRouteImport } from './routes/why'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as HotelsSlugRouteImport } from './routes/hotels.$slug'
import { Route as HotelsSlugGalleryRouteImport } from './routes/hotels.$slug_.gallery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/admin/history',
  path: '/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsSlugRoute = HotelsSlugRouteImport.update({
  id: '/hotels/$slug',
  path: '/hotels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsSlugGalleryRoute = HotelsSlugGalleryRouteImport.update({
  id: '/hotels/$slug_/gallery',
  path: '/hotels/$slug/gallery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/why': typeof WhyRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/$slug/gallery': typeof HotelsSlugGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/why': typeof WhyRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/hotels/$slug/gallery': typeof HotelsSlugGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/why': typeof WhyRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/hotels/$slug_/gallery': typeof HotelsSlugGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/privacy'
    | '/terms'
    | '/why'
    | '/admin/history'
    | '/admin/login'
    | '/hotels/$slug'
    | '/admin/'
    | '/hotels/$slug/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/privacy'
    | '/terms'
    | '/why'
    | '/admin/history'
    | '/admin/login'
    | '/hotels/$slug'
    | '/admin'
    | '/hotels/$slug/gallery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/privacy'
    | '/terms'
    | '/why'
    | '/admin/history'
    | '/admin/login'
    | '/hotels/$slug'
    | '/admin/'
    | '/hotels/$slug_/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WhyRoute: typeof WhyRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  HotelsSlugRoute: typeof HotelsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HotelsSlugGalleryRoute: typeof HotelsSlugGalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/admin/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$slug': {
      id: '/hotels/$slug'
      path: '/hotels/$slug'
      fullPath: '/hotels/$slug'
      preLoaderRoute: typeof HotelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$slug_/gallery': {
      id: '/hotels/$slug_/gallery'
      path: '/hotels/$slug/gallery'
      fullPath: '/hotels/$slug/gallery'
      preLoaderRoute: typeof HotelsSlugGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WhyRoute: WhyRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  HotelsSlugRoute: HotelsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  HotelsSlugGalleryRoute: HotelsSlugGalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
